# Generated by Django 5.2.6 on 2025-11-22 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(help_text='ID đơn hàng từ Orders Service')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Tổng doanh thu', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Tổng chi phí', max_digits=10)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, help_text='Tổng lợi nhuận', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(help_text='ID sản phẩm từ Products Service')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_sold', models.IntegerField(default=0, help_text='Tổng số lượng đã bán')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, help_text='Doanh thu', max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='Chi phí', max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, help_text='Lợi nhuận', max_digits=10)),
                ('order_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reports', to='reports.orderreport')),
            ],
            options={
                'db_table': 'product_reports',
            },
        ),
    ]
